version: 2.1

shared: &shared
  context: org-global

orbs:
  android: circleci/android@2
  node: circleci/node@5

jobs:
  android:
    executor:
      name: android/android-machine
      tag: 202102-01
    steps:
      - checkout
      - node/install-packages
      - android/create-avd:
          avd-name: test
          install: true
          system-image: "system-images;android-29;default;x86"
      - android/start-emulator:
          avd-name: test
          post-emulator-launch-assemble-command: ""
      - android/run-tests:
          working-directory: android
      - android/kill-emulators

# iOS testing command
# https://www.appsdeveloperblog.com/run-xcode-unit-tests-from-the-command-line/
# xcodebuild build-for-testing -workspace Plugin.xcworkspace -scheme PluginTests -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.4'
# xcodebuild test -workspace Plugin.xcworkspace -scheme PluginTests -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.4'

workflows:
  default:
    jobs:
      - android:
          <<: *shared
          name: android
